#server:
# port: 8080
 
#spring:
#  security:
#    user:
#      name: akash
#      password: akash

#spring:
# datasource:
     # url: jdbc:mysql://10.0.2.134:3306/jwt-token?serverTimezone=UTC
    #  username: akashk
     # password: Akash@SQL_DB
      
 #jpa:
   # hibernate.ddl-auto: update
   # generate-ddl: true
   # show-sql: true